# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    env:
          SONAR_TOKEN: Qwerty123456
        
    steps:
      - name: "Prueba de concepto; Primer GH"
        run: echo "Primer GH - " date
      
      - name: "Prueba con secretos & variables de entorno"
        run: echo "env 'sonar :' $SONAR_TOKEN"
      
