# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    env:
          vataible01: Qwerty123456
          vataible02: "soy batman"
          vataible03: "123487"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
        
    steps:
      - name: "Prueba de concepto; Primer GH"
        run: echo "Primer GH - xxxxxxx "
      
      - name: "Prueba con secretos & variables de entorno"
        run: | 
          echo "01 : ${{env.vataible01}}"
          echo "02 : ${{env.vataible02}}"
          echo "03 : ${{env.vataible03}}"
          echo "04 : ${{GITHUB_TOKEN}}"
      
